// supplier1.js
// Auto-generated from Supplier 1.pdf

window.supplier2Products = [
  "Acifar 400mg tablet 30s",
  "Acifar cream 5gr",
  "Acnes Sealing Jell 9gr",
  "ACYCLOVIR cream 5% Erella",
  "Alerzin syr 60ml",
  "Alerzin tab 10x10s",
  "Allergen 4mg Box",
  "Alletrol Salep Mata",
  "Alletrol tts mata",
  "ALLOPURINOL 300mg HEXAPHARM 10x10s",
  "Alofar 100mg",
  "Alphamol kaplet box",
  "Amlodipine 10mg Medicon 30s",
  "Amlodipine 5mg Medicon 30s",
  "Amlodipine tab 5mg Interbat",
  "Anabion syr",
  "Anacetin syr 60ml",
  "Anakonidin 30ml",
  "Anakonidin 60ml",
  "Anastan forte",
  "Anaton syr",
  "Anoral Anliq 30s",
  "Antacida Doen 20mg 100s tab Erella",
  "ANTACIDA DOEN SUSPENSI 60ml Erella",
  "Axofen syr",
  "Baby cough Pacdin original syr",
  "Baby cough Pacdin strawberry syr",
  "BENOSTAN 500mg Kaplet 10x10s",
  "Betadin Solution 5ml (Box @ 6 botol)",
  "Betamol kaplet strip / H",
  "Betason N cream",
  "Bioplacenton",
  "Braito original 5ml",
  "Broadamox DS",
  "Bronchitin syr 60ml",
  "Bufacaril",
  "Bufacort N cream",
  "Bufantacid forte syr",
  "Bufantacid tab",
  "Calcifar kaplet",
  "Calcifar plus capl",
  "Carbidu 0.5mg",
  "Cavicur DHA + Prebiotik",
  "Caviplex CDEZ Kaplet 100s",
  "CETIRIZIN 10mg HEXPHARM 100s",
  "Coldrexin syr 60ml",
  "Colfin Plus syr",
  "Colfin syr 60ml",
  "Coparcetin kid-cough syr",
  "Coparcetin syr 60ml",
  "Cordema-N krim 5gr",
  "Coredryl syrHal : 1/26",
  "Costan Forte 500mg",
  "Counterpain 5gr",
  "Danason 0,5mg",
  "Darsi kapsul",
  "Demacolin tab",
  "Dexteem plus",
  "DEXTRAL syr",
  "DICLOFENAC SODIUM 50mg Samco",
  "Domperidone 10mg Erlimpex / M",
  "Domperidone suspensi 60ml Erlimpex / M",
  "Em kapsul",
  "Emturnas 500mg capl",
  "Emturnas syr",
  "Enbatic Salep Kulit 10gr",
  "Erla neo hydrocort cream 5gr",
  "Erladerm-N 5gr",
  "Erlamol 500mg tablet box",
  "Erllamicetin salaf mata",
  "Erllamicetin tetes mata Plus",
  "Erllamicetin tetes telinga",
  "Ermethason 0,75mg",
  "Erphaflam tab salut gula 5x10s",
  "Erphakaf plus syr 60ml",
  "Erphamol syr 60ml",
  "Etafenin kaplet",
  "Etaflusin kaplet",
  "Etamox Ds",
  "Farsifen suspensi",
  "Fasidol drop 15ml",
  "Fasidol forte 650mg kaplet",
  "Fasidol forte syr",
  "Fasidol kaplet strip",
  "Fasiprim syr",
  "Floxifar 500mg",
  "Flucadex kaplet",
  "Flucadex syr",
  "Flunadin tablet",
  "Flutop C syr",
  "Folacite 400 tablet",
  "Fungiderm 5gr",
  "Gastrucid syr 60ml",
  "Gastrucid tab",
  "Genoint 0.3% salep mata",
  "Genoint salep kulit 15gr",
  "Genoint tetes mata 5ml",
  "Glikos 500mg",
  "Glimepiride 2mg Hexpharm 100s",
  "Gradilex 2mg 100s",
  "Grafadon forte tab",
  "Grantusif kaplet",
  "Grathazon",
  "Grazeo 20mg",
  "GUAIFENESIN 50mg Pot 100s Erlimpex",
  "HELIXIM DS 30mlHal : 6/26",
  "HELIXIM Kapsul 30s",
  "HOTIN CREAM STRONG 60gr Tube",
  "Hufabion tab",
  "Ifarsyl plus syr",
  "Inflason",
  "Insto 7.5ml",
  "Insto Cool",
  "Insto Dry Eyes 7.5ml",
  "Intunal syr 60ml",
  "Itamol kaplet Berlico",
  "Itrabat syr 100ml",
  "Kaditic 50mg 10x10s",
  "Kalpanax cream 10gr",
  "Kalpanax cream 5gr",
  "KANA CREAM 30gr",
  "Kandistatin drop",
  "KANINA suspensi 60ml",
  "Kaotin syr",
  "KASA KOTAK HK 16x16 12s",
  "Katusi kapsul 30s",
  "Kembang bulan ( KAPSIDA )",
  "Ketoconazole cream 2% 10gr Dexa Medica",
  "Ketoconazole tablet 200mg Hexpharm 100s",
  "Klorfeson cream",
  "Kondom fiesta Strawberry 3s",
  "Kondom fiesta Watermelon 3s",
  "Lansoprazole 30mg Nufarindo",
  "Laserin madu 30ml Box ( 4 x 30ml )",
  "Lerzin syr",
  "Lexcomet Tablet",
  "LORIHIS tablet",
  "Lostacef 500mg caps 100s",
  "Madu TJ Jeruk sachet",
  "Maggel suspensi",
  "Magic power Hitam",
  "Magic Power Merah",
  "MANTINO 50mg",
  "Mefenamic Acid 500mg TRIFA 10x10s",
  "Mexon",
  "Micazol 2% cream 5gr",
  "Microlax 5mg",
  "Microlax tab 1x10s",
  "Mirasic 500mg strip",
  "Mirasic syr",
  "Mixalgin",
  "Moladerm cream",
  "Molafate suspensi",
  "Molexflu kaplet",
  "Mucos syr 60ml",
  "Mycoral cream",
  "Mylanta syr 50mlHal : 11/26",
  "NACL / Natrium clorida. Otsuka",
  "Nisagon cream",
  "Novaxicam 20mg kapsul",
  "Nufacort cream 5gr",
  "Nufadol syr",
  "Nufaflu syr 60ml",
  "Obat gigi cap kakak tua",
  "OBH Itrasal syr 100ml",
  "OBH Nellco Batuk Berdahak 100ml",
  "OBP Itrasal syr 100ml",
  "Orphen tablet box",
  "Paracetamol 500mg Kaplet TRIFA 10x10s",
  "Paracetamol Drops 15ml Ifars",
  "Paracetine Kaplet 10x10s",
  "Paracetine syr",
  "Paraflu syr 60ml",
  "PARAMOL 500mg Kaplet 10x10s",
  "Paratusin syr",
  "PIMTRACOL KIDS",
  "Pimtracol plus Lemon syr",
  "Piroxicam tablet 20mg Trifa",
  "Plantacid Forte syr 100ml",
  "Polopar plus",
  "Polysilane suspensi 100ml",
  "Polysilane tablet",
  "Pronicy",
  "Proris suspensi Forte",
  "Reco salep mata",
  "Reco tetes mata 10ml",
  "Reco tetes telinga",
  "Redoxon Eff Zink Orange tab 10s",
  "Sakatonik ABC tab hisap anggur",
  "Sakatonik ABC tab hisap Antariksa",
  "Sakatonik ABC tab hisap jeruk",
  "Sakatonik ABC tab hisap straw",
  "Salep Seriti 10gr",
  "Samcofenac 50mg tablet",
  "Samtacid tablet",
  "SANADRYL Ekspektoran 60ml",
  "SANMAG SUSPENSI 120ml",
  "Sanmol drop",
  "Sanmol Forte Tablet",
  "Sanmol syr",
  "Sanmol tab 4x25",
  "SCABIMITE 10gr",
  "Sidiadryl Injeksi ( Box @ 10 Vial )",
  "Siladex Antitusive syr 60ml / Merah",
  "Siladex Batuk & Pilek syr 100ml",
  "Siladex Batuk Berdahak Mucolytic Expec syr 30ml",
  "Siladex Cough & Flu 60ml",
  "SIMVASTATIN 10mg Hexpharm",
  "Solinfec cream 5grHal : 18/26",
  "Solinfec tablet",
  "SUCRALFATE syr 100ml Combiphar",
  "SUPER MAGIC Man / Hitam",
  "SUPER MAGIC Man Casanova / Merah",
  "Superhoid supp",
  "Tempra syr 30ml Grape",
  "Teosal tablet",
  "Termorex plus 30ml",
  "Tonikum bayer 330ml",
  "Triocid syr 60ml",
  "Triocid tab",
  "Vesperum suspensi",
  "Vesperum tab",
  "Vick formula 44 27ml dewasa",
  "Vick formula 44 54ml anak straw",
  "Vick formula 44 anak Strawberry 27 ml",
  "Vick Inhaler Key Chain (Box @ 1 pcs)",
  "Vidoran smart tab Strawberry 25s",
  "Vitacimin Orange tablet hisap",
  "Voltadex 50mg 100s",
  "Wiros",
  "Woods obat batuk Expetoran 60ml",
  "Yusimox 500mg",
  "Yusimox DS",
  "Zoralin cream 2% 10grHal : 25/26",
];